language: ruby
rvm:
- 2.4.5
- 2.3.8
cache:
  bundler: true
  yarn: true
  timeout: 600
addons:
  postgresql: '9.5'
env:
  matrix:
  - TEST_SUITE=spec
  - TEST_SUITE=spec:javascript
  - TEST_SUITE=spec:compile
  - TEST_SUITE=spec:jest
matrix:
  exclude:
  - rvm: 2.4.5
    env: TEST_SUITE=spec:javascript
  - rvm: 2.4.5
    env: TEST_SUITE=spec:compile
  - rvm: 2.4.5
    env: TEST_SUITE=spec:jest
bundler_args: "--no-deployment"
before_install: source tools/ci/before_install.sh
install: true
script: bundle exec rake $TEST_SUITE
after_script: source tools/ci/after_install.sh
branches:
 only:
  -dev
